# Generated by Django 3.1.3 on 2020-12-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201203_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='neighbourhood_admin',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='system_admin',
            new_name='is_superuser',
        ),
    ]
