# Generated by Django 3.1.3 on 2020-12-04 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201204_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hood'),
        ),
    ]
