# Generated by Django 3.1.3 on 2020-12-04 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201204_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.hood'),
        ),
    ]
