# Generated by Django 3.1.3 on 2020-12-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201204_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
